---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace
      - id: check-yaml # Validates YAML files
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer # Ensures files end with a newline
      - id: check-toml # Validates TOML files
      - id: check-json # Validates JSON files
      - id: check-xml # Validates XML files
      - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Checks for files that contain merge conflict strings
      - id: check-added-large-files # Checks for large files added to the repo
      - id: check-executables-have-shebangs # Checks that executables have shebangs
      - id: detect-private-key # Checks for the existence of private keys
      - id: mixed-line-ending # Enforce LF line endings in text files
        args: [--fix=lf]

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.1
    hooks:
      - id: check-json5

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.23.0
    hooks:
      - id: markdownlint-cli2
        pass_filenames: false

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck # Shell scripts conform to shellcheck
      - id: shfmt # Check shell style with shfmt

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: [--config-data, relaxed, --no-warnings]

  - repo: https://github.com/looztra/yamkix
    rev: v1.1.0
    hooks:
      - id: yamkix
        args: [--no-quotes-preserved, --silent]

  - repo: local
    hooks:
      - id: taplo
        name: Check TOML files are formatted with 'taplo'
        entry: taplo format --config .taplo.toml
        types: [text]
        language: system
        pass_filenames: false
